database:

  driverClass: org.postgresql.Driver
  user: vhmit005
  password:
  url: jdbc:postgresql://localhost:5432/emilena

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

server:

  applicationConnectors:
    - type: http
      port: 9090

  adminConnectors:
    - type: http
      port: 9091
